# Theme Settings
# theme              : "minimal-mistakes-jekyll"
# remote_theme       : "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale         : "en-US"
title          : Scott Wu
title_separator: "-"
name           : "Scott Wu"
description    : "This is my site"
url            : "https://blog.scwu.io"
baseurl        : ""
repository     : "ScottSWu/scottswu.github.io"

# File Settings
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion Settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Output Settings
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/New_York

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

include:
  - _pages
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .gitignore
  - .sass-cache
  - .vscode
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Gemfile
  - Gemfile.lock
  - old
  - vendor
  - projects

# Site Author
author:
  name    : "Scott Wu"
  avatar  : "/assets/images/avatar.jpg"
  email   : "me@scwu.io"
  github  : "ScottSWu"
  linkedin: "scswu"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
